-- Drop existing tables if present
DROP TABLE notifications CASCADE CONSTRAINTS;
DROP TABLE order_items CASCADE CONSTRAINTS;
DROP TABLE orders CASCADE CONSTRAINTS;
DROP TABLE subscriptions CASCADE CONSTRAINTS;
DROP TABLE prescriptions CASCADE CONSTRAINTS;
DROP TABLE cart_items CASCADE CONSTRAINTS;
DROP TABLE carts CASCADE CONSTRAINTS;
DROP TABLE medicines CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;

-- Drop Sequences
DROP SEQUENCE SEQ_USERS;
DROP SEQUENCE SEQ_MEDICINES;
DROP SEQUENCE SEQ_CARTS;
DROP SEQUENCE SEQ_CART_ITEMS;
DROP SEQUENCE SEQ_PRESCRIPTIONS;
DROP SEQUENCE SEQ_SUBSCRIPTIONS;
DROP SEQUENCE SEQ_ORDERS;
DROP SEQUENCE SEQ_ORDER_ITEMS;
DROP SEQUENCE SEQ_NOTIFICATIONS;

-- Create Sequences
CREATE SEQUENCE SEQ_USERS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEDICINES START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CARTS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CART_ITEMS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRESCRIPTIONS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SUBSCRIPTIONS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDERS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDER_ITEMS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTIFICATIONS START WITH 100 INCREMENT BY 1;

-- Users Table
CREATE TABLE users (
    id NUMBER(19) DEFAULT SEQ_USERS.NEXTVAL PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'PATIENT' NOT NULL,
    phone VARCHAR2(20),
    address VARCHAR2(255),
    city VARCHAR2(100),
    state VARCHAR2(100),
    pincode VARCHAR2(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Medicines Table
CREATE TABLE medicines (
    id NUMBER(19) DEFAULT SEQ_MEDICINES.NEXTVAL PRIMARY KEY,
    medicine_name VARCHAR2(150) NOT NULL,
    brand_name VARCHAR2(100) NOT NULL,
    composition VARCHAR2(150) NOT NULL,
    strength VARCHAR2(50) NOT NULL,
    category VARCHAR2(50),
    price NUMBER(10, 2) NOT NULL,
    stock_quantity NUMBER(10) DEFAULT 0 NOT NULL,
    requires_prescription NUMBER(1) DEFAULT 0 NOT NULL,
    description CLOB,
    manufacturer VARCHAR2(100),
    expiry_date TIMESTAMP,
    active NUMBER(1) DEFAULT 1 NOT NULL
);

-- Carts Table
CREATE TABLE carts (
    id NUMBER(19) DEFAULT SEQ_CARTS.NEXTVAL PRIMARY KEY,
    patient_id NUMBER(19) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Cart Items Table
CREATE TABLE cart_items (
    id NUMBER(19) DEFAULT SEQ_CART_ITEMS.NEXTVAL PRIMARY KEY,
    cart_id NUMBER(19) NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    medicine_id NUMBER(19) NOT NULL REFERENCES medicines(id),
    quantity NUMBER(10) NOT NULL,
    price_at_addition NUMBER(10, 2) NOT NULL
);

-- Prescriptions Table
CREATE TABLE prescriptions (
    id NUMBER(19) DEFAULT SEQ_PRESCRIPTIONS.NEXTVAL PRIMARY KEY,
    patient_id NUMBER(19) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    file_name VARCHAR2(255) NOT NULL,
    file_path VARCHAR2(500) NOT NULL,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiry_date TIMESTAMP NOT NULL,
    doctor_visit_date TIMESTAMP,
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL
);

-- Subscriptions Table
CREATE TABLE subscriptions (
    id NUMBER(19) DEFAULT SEQ_SUBSCRIPTIONS.NEXTVAL PRIMARY KEY,
    patient_id NUMBER(19) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    medicine_id NUMBER(19) REFERENCES medicines(id),
    prescription_id NUMBER(19) REFERENCES prescriptions(id) ON DELETE SET NULL,
    dosage VARCHAR2(50),
    frequency VARCHAR2(50),
    quantity NUMBER(10),
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    next_refill_date TIMESTAMP,
    next_dispatch_date TIMESTAMP,
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Orders Table
CREATE TABLE orders (
    id NUMBER(19) DEFAULT SEQ_ORDERS.NEXTVAL PRIMARY KEY,
    patient_id NUMBER(19) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subscription_id NUMBER(19) REFERENCES subscriptions(id) ON DELETE SET NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount NUMBER(10, 2) NOT NULL,
    delivery_address VARCHAR2(500) NOT NULL,
    payment_method VARCHAR2(50) DEFAULT 'CASH_ON_DELIVERY',
    payment_status VARCHAR2(30) DEFAULT 'PENDING',
    order_status VARCHAR2(30) DEFAULT 'PENDING',
    order_type VARCHAR2(30) DEFAULT 'ONE_TIME',
    expected_delivery_date TIMESTAMP
);

-- Order Items Table
CREATE TABLE order_items (
    id NUMBER(19) DEFAULT SEQ_ORDER_ITEMS.NEXTVAL PRIMARY KEY,
    order_id NUMBER(19) NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    medicine_id NUMBER(19) NOT NULL REFERENCES medicines(id),
    quantity NUMBER(10) NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL
);

-- Notifications Table
CREATE TABLE notifications (
    id NUMBER(19) DEFAULT SEQ_NOTIFICATIONS.NEXTVAL PRIMARY KEY,
    user_id NUMBER(19) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR2(255) NOT NULL,
    message CLOB NOT NULL,
    type VARCHAR2(30) DEFAULT 'INFO',
    is_read NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
