-- Drop existing tables if present
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS prescriptions CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS medicines CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Drop Sequences
DROP SEQUENCE IF EXISTS SEQ_USERS;
DROP SEQUENCE IF EXISTS SEQ_MEDICINES;
DROP SEQUENCE IF EXISTS SEQ_CARTS;
DROP SEQUENCE IF EXISTS SEQ_CART_ITEMS;
DROP SEQUENCE IF EXISTS SEQ_PRESCRIPTIONS;
DROP SEQUENCE IF EXISTS SEQ_SUBSCRIPTIONS;
DROP SEQUENCE IF EXISTS SEQ_ORDERS;
DROP SEQUENCE IF EXISTS SEQ_ORDER_ITEMS;
DROP SEQUENCE IF EXISTS SEQ_NOTIFICATIONS;

-- Create Sequences
CREATE SEQUENCE SEQ_USERS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEDICINES START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CARTS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CART_ITEMS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRESCRIPTIONS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SUBSCRIPTIONS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDERS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDER_ITEMS START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTIFICATIONS START WITH 100 INCREMENT BY 1;

-- Users Table
CREATE TABLE users (
    id BIGINT DEFAULT nextval('SEQ_USERS') PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'PATIENT' NOT NULL,
    phone VARCHAR(20),
    address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Medicines Table
CREATE TABLE medicines (
    id BIGINT DEFAULT nextval('SEQ_MEDICINES') PRIMARY KEY,
    medicine_name VARCHAR(150) NOT NULL,
    brand_name VARCHAR(100) NOT NULL,
    composition VARCHAR(150) NOT NULL,
    strength VARCHAR(50) NOT NULL,
    category VARCHAR(50),
    price NUMERIC(10, 2) NOT NULL,
    stock_quantity INTEGER DEFAULT 0 NOT NULL,
    requires_prescription SMALLINT DEFAULT 0 NOT NULL,
    description TEXT,
    manufacturer VARCHAR(100),
    expiry_date TIMESTAMP,
    active SMALLINT DEFAULT 1 NOT NULL
);

-- Carts Table
CREATE TABLE carts (
    id BIGINT DEFAULT nextval('SEQ_CARTS') PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Cart Items Table
CREATE TABLE cart_items (
    id BIGINT DEFAULT nextval('SEQ_CART_ITEMS') PRIMARY KEY,
    cart_id BIGINT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    medicine_id BIGINT NOT NULL REFERENCES medicines(id),
    quantity INTEGER NOT NULL,
    price_at_addition NUMERIC(10, 2) NOT NULL
);

-- Prescriptions Table
CREATE TABLE prescriptions (
    id BIGINT DEFAULT nextval('SEQ_PRESCRIPTIONS') PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiry_date TIMESTAMP NOT NULL,
    doctor_visit_date TIMESTAMP,
    status VARCHAR(30) DEFAULT 'PENDING' NOT NULL
);

-- Subscriptions Table
CREATE TABLE subscriptions (
    id BIGINT DEFAULT nextval('SEQ_SUBSCRIPTIONS') PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    medicine_id BIGINT REFERENCES medicines(id),
    prescription_id BIGINT REFERENCES prescriptions(id) ON DELETE SET NULL,
    dosage VARCHAR(50),
    frequency VARCHAR(50),
    quantity INTEGER,
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    next_refill_date TIMESTAMP,
    next_dispatch_date TIMESTAMP,
    status VARCHAR(30) DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Orders Table
CREATE TABLE orders (
    id BIGINT DEFAULT nextval('SEQ_ORDERS') PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subscription_id BIGINT REFERENCES subscriptions(id) ON DELETE SET NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount NUMERIC(10, 2) NOT NULL,
    delivery_address VARCHAR(500) NOT NULL,
    payment_method VARCHAR(50) DEFAULT 'CASH_ON_DELIVERY',
    payment_status VARCHAR(30) DEFAULT 'PENDING',
    order_status VARCHAR(30) DEFAULT 'PENDING',
    order_type VARCHAR(30) DEFAULT 'ONE_TIME',
    expected_delivery_date TIMESTAMP
);

-- Order Items Table
CREATE TABLE order_items (
    id BIGINT DEFAULT nextval('SEQ_ORDER_ITEMS') PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    medicine_id BIGINT NOT NULL REFERENCES medicines(id),
    quantity INTEGER NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL
);

-- Notifications Table
CREATE TABLE notifications (
    id BIGINT DEFAULT nextval('SEQ_NOTIFICATIONS') PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(30) DEFAULT 'INFO',
    is_read SMALLINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
